apiVersion: v1
kind: Pod
metadata:
  name: kuard
  labels:
    name: kuard
spec:
  containers:
  - name: kuard
    image: samueltang/kuard-demo:blue
    ports:
      - containerPort: 8080
        name: http
        protocol: TCP
  imagePullSecrets:
    - name: myregistrykey