apiVersion: v1
kind: Pod
metadata:
  name: kuard
  labels:
    name: kuard
spec:
  volumes:
    - name: "kuard-data"
      hostPath:
        path: "/var/lib/kuard"
  containers:
  - name: kuard
    image: samueltang/kuard-demo:blue
    volumeMounts:
      - mountPath: "/data"
        name: "kuard-data"
    ports:
      - containerPort: 8080
        name: http
        protocol: TCP
  imagePullSecrets:
    - name: myregistrykey