apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpaca-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: alpaca
  template:
    metadata:
      labels:
        ver: "1"
        app: alpaca
        env: prod
    spec:
      containers:
      - name: alpaca-prod
        image: samueltang/kuard-demo:blue
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
      imagePullSecrets:
        - name: myregistrykey