apiVersion: v1
kind: Pod
metadata:
  name: kuard
  labels:
    name: kuard
spec:
  containers:
  - name: kuard
    image: samueltang/kuard-demo:blue
    resources:
      requests:
        cpu: "500m"
        memory: "128Mi"
      limits:
        cpu: "1000m"
        memory: "256Mi"
    ports:
      - containerPort: 8080
        name: http
        protocol: TCP
  imagePullSecrets:
    - name: myregistrykey