apiVersion: v1
kind: Secret
metadata:
  name: myregistrykey
  namespace: default
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImMyRnRkV1ZzZEdGdVp6cFRZVzExWld4QVpHOWphMlZ5IgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson